(async()=>{
const K='harcama_ios_v2',IK='harcama_income_v1',B='harcama_budget_v2',L='harcama_pin_v1',$=i=>document.getElementById(i),fmt=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(+n||0),pad=n=>String(n).padStart(2,'0'),today=()=>{const d=new Date;return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())},mon=()=>today().slice(0,7),year=()=>today().slice(0,4),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),sum=a=>a.reduce((s,i)=>s+(+i.amount||0),0);
let x=[],inc=[],editId=null,balanceMode='month';try{x=JSON.parse(localStorage.getItem(K)||'[]')}catch{}try{inc=JSON.parse(localStorage.getItem(IK)||'[]')}catch{}if(!Array.isArray(x))x=[];if(!Array.isArray(inc))inc=[];
$('date').value=today();$('incomeDate').value=today();$('budget').value=localStorage.getItem(B)||'';$('homeMonth').value=mon();$('listMonth').value=mon();$('balanceMonth').value=mon();$('monthLabel').textContent=new Intl.DateTimeFormat('tr-TR',{month:'long',year:'numeric'}).format(new Date());
function buildYears(){const ys=new Set([+year()]);x.forEach(i=>ys.add(+String(i.date).slice(0,4)));inc.forEach(i=>ys.add(+String(i.date).slice(0,4)));for(let y=+year()-3;y<=+year()+1;y++)ys.add(y);$('balanceYear').innerHTML=[...ys].filter(Number.isFinite).sort((a,b)=>b-a).map(y=>'<option'+(String(y)===year()?' selected':'')+'>'+y+'</option>').join('')}
buildYears();
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('on',p.id===id));document.querySelectorAll('.nav button').forEach(n=>n.classList.toggle('on',n.dataset.p===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='balance')renderBalance()}
document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.p)));
$('f').addEventListener('submit',e=>{e.preventDefault();const a=+$('amount').value;if(!(a>0))return alert('Geçerli bir tutar gir.');const item={id:editId||Date.now(),date:$('date').value,amount:Math.round(a*100)/100,cat:$('cat').value,pay:$('pay').value,desc:$('desc').value.trim()};if(editId){const i=x.findIndex(v=>String(v.id)===String(editId));if(i>=0)x[i]=item}else x.push(item);save();resetForm();render();showPage('home')});
function resetForm(){editId=null;$('date').value=today();$('amount').value='';$('desc').value='';$('cat').value='Market';$('pay').value='Nakit';$('formTitle').textContent='Yeni Harcama';$('normalActions').style.display='grid';$('editActions').style.display='none'}
$('cancelEdit').addEventListener('click',()=>{resetForm();showPage('list')});
$('incomeForm').addEventListener('submit',e=>{e.preventDefault();const a=+$('incomeAmount').value;if(!(a>0))return alert('Geçerli bir gelir tutarı gir.');inc.push({id:'i'+Date.now(),date:$('incomeDate').value,amount:Math.round(a*100)/100,cat:$('incomeCat').value,desc:$('incomeDesc').value.trim()});saveIncome();$('incomeAmount').value='';$('incomeDesc').value='';$('incomeDate').value=today();buildYears();render();renderBalance()});
$('saveBudget').addEventListener('click',()=>{const v=+$('budget').value;if(!Number.isFinite(v)||v<0)return alert('Geçerli bir bütçe gir.');localStorage.setItem(B,String(v));render()});
['homeMonth','listMonth','filterCat','search'].forEach(id=>$(id).addEventListener('input',render));$('balanceMonth').addEventListener('input',renderBalance);$('balanceYear').addEventListener('change',renderBalance);
$('modeMonth').addEventListener('click',()=>setBalanceMode('month'));$('modeYear').addEventListener('click',()=>setBalanceMode('year'));
function setBalanceMode(m){balanceMode=m;$('modeMonth').classList.toggle('on',m==='month');$('modeYear').classList.toggle('on',m==='year');$('periodRow').classList.toggle('year',m==='year');$('yearTableWrap').style.display=m==='year'?'block':'none';renderBalance()}
$('items').addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const id=b.dataset.id;if(b.dataset.action==='delete'&&confirm('Bu kayıt silinsin mi?')){x=x.filter(i=>String(i.id)!==id);save();render();renderBalance()}if(b.dataset.action==='edit'){const i=x.find(v=>String(v.id)===id);if(!i)return;editId=i.id;$('date').value=i.date;$('amount').value=i.amount;$('cat').value=i.cat;$('pay').value=i.pay;$('desc').value=i.desc||'';$('formTitle').textContent='Harcamayı Düzenle';$('normalActions').style.display='none';$('editActions').style.display='grid';showPage('add')}});
$('incomeItems').addEventListener('click',e=>{const b=e.target.closest('button[data-income-delete]');if(!b)return;const id=b.dataset.incomeDelete;if(confirm('Bu gelir kaydı silinsin mi?')){inc=inc.filter(i=>String(i.id)!==id);saveIncome();buildYears();render();renderBalance()}});
$('clear').addEventListener('click',()=>{if((x.length||inc.length)&&confirm('Tüm gelir ve harcama kayıtları silinsin mi? Bu işlem geri alınamaz.')){x=[];inc=[];save();saveIncome();resetForm();buildYears();render();renderBalance()}});
function download(name,text,type){const blob=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('backup').addEventListener('click',()=>download('finans-yedek.json',JSON.stringify({version:4,exportedAt:new Date().toISOString(),expenses:x,incomes:inc,budget:+(localStorage.getItem(B)||0)},null,2),'application/json'));
$('csv').addEventListener('click',()=>{const tx=[...x.map(i=>({type:'Gider',...i})),...inc.map(i=>({type:'Gelir',...i,pay:''}))].sort((a,b)=>a.date.localeCompare(b.date)),rows=[['Tür','Tarih','Kategori','Açıklama','Ödeme','Tutar'],...tx.map(i=>[i.type,i.date,i.cat,i.desc||'',i.pay||'',i.amount])];const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\n');download('gelir-gider.csv',csv,'text/csv;charset=utf-8')});
async function hash(s){const data=new TextEncoder().encode(s),buf=await crypto.subtle.digest('SHA-256',data);return[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function updateLockUI(){const has=!!localStorage.getItem(L);$('removePin').disabled=!has;$('removePin').style.opacity=has?'1':'.45';$('pinMsg').textContent=has?'Uygulama kilidi açık.':'Uygulama kilidi kapalı.'}
$('savePin').addEventListener('click',async()=>{const a=$('newPin').value,b=$('newPin2').value;if(!/^\d{4,6}$/.test(a))return $('pinMsg').textContent='PIN 4–6 rakam olmalı.';if(a!==b)return $('pinMsg').textContent='PIN değerleri aynı değil.';localStorage.setItem(L,await hash(a));$('newPin').value='';$('newPin2').value='';await updateLockUI();$('pinMsg').textContent='PIN kaydedildi.'});
$('removePin').addEventListener('click',()=>{if(localStorage.getItem(L)&&confirm('Uygulama kilidi kapatılsın mı?')){localStorage.removeItem(L);updateLockUI()}});
$('unlockBtn').addEventListener('click',async()=>{const p=$('unlockPin').value;if(await hash(p)===localStorage.getItem(L)){$('lock').classList.remove('on');$('unlockPin').value='';$('unlockMsg').textContent=''}else{$('unlockMsg').textContent='PIN hatalı.';$('unlockPin').select()}});$('unlockPin').addEventListener('keydown',e=>{if(e.key==='Enter')$('unlockBtn').click()});
function save(){localStorage.setItem(K,JSON.stringify(x))}function saveIncome(){localStorage.setItem(IK,JSON.stringify(inc))}
function render(){const cm=mon(),m=x.filter(i=>String(i.date).slice(0,7)===cm),mi=inc.filter(i=>String(i.date).slice(0,7)===cm),ms=sum(m),is=sum(mi),net=is-ms;$('mt').textContent=fmt(ms);$('mit').textContent=fmt(is);$('mc').textContent=m.length+' kayıt';$('mic').textContent=mi.length+' gelir kaydı';$('mnet').textContent=fmt(net);$('mnet').className='val '+(net>0?'good':net<0?'bad':'');$('mnetSub').textContent=net>0?'Bu ay kârdasın':net<0?'Bu ay zarardasın':'Gelir - gider';const bu=+(localStorage.getItem(B)||0);if(bu>0){const r=bu-ms,p=ms/bu*100;$('remain').textContent=(r<0?'-':'')+fmt(Math.abs(r));$('remain').style.color=r<0?'var(--red)':'var(--text)';$('remainSub').textContent=r<0?'Bütçe aşıldı':'Kullanılabilir';$('bi').innerHTML=(r>=0?'Kalan ':'Aşılan ')+'<strong>'+fmt(Math.abs(r))+'</strong>';$('budgetPct').textContent=Math.round(p)+'%';$('bar').style.width=Math.min(100,Math.max(0,p))+'%';$('bar').style.background=p>=100?'#d92d20':p>=80?'#dc6803':'var(--blue)'}else{$('remain').textContent='—';$('remain').style.color='var(--text)';$('remainSub').textContent='Bütçe belirlenmedi';$('bi').textContent='Bütçe belirlenmedi.';$('budgetPct').textContent='';$('bar').style.width='0'}const hm=$('homeMonth').value||cm,hmItems=x.filter(i=>String(i.date).slice(0,7)===hm),tot={},hmSum=sum(hmItems);hmItems.forEach(i=>tot[i.cat]=(tot[i.cat]||0)+(+i.amount||0));const arr=Object.entries(tot).sort((a,b)=>b[1]-a[1]),mx=arr[0]?.[1]||1;$('cats').innerHTML=arr.length?arr.map(([k,v])=>'<div class="chartRow"><div class="chartName">'+esc(k)+'</div><div class="track"><div class="fill" style="width:'+Math.max(4,v/mx*100)+'%"></div></div><div class="chartValue">'+fmt(v)+'<div class="pct">'+(hmSum?Math.round(v/hmSum*100):0)+'%</div></div></div>').join(''):'<div class="empty">Bu ay için harcama yok.</div>';const lm=$('listMonth').value||cm,fc=$('filterCat').value,q=$('search').value.trim().toLocaleLowerCase('tr-TR');let rows=x.filter(i=>String(i.date).slice(0,7)===lm);if(fc)rows=rows.filter(i=>i.cat===fc);if(q)rows=rows.filter(i=>(i.desc||'').toLocaleLowerCase('tr-TR').includes(q));rows.sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.id).localeCompare(String(a.id)));$('listInfo').textContent=rows.length+' kayıt • '+fmt(sum(rows));$('items').innerHTML=rows.length?rows.map(i=>'<div class="item"><div class="itemTop"><div><div class="itemCat">'+esc(i.cat)+'</div><div class="itemDesc">'+esc(i.desc||'-')+'</div></div><div class="itemAmt">'+fmt(i.amount)+'</div></div><div class="meta">'+esc(i.date)+' • '+esc(i.pay||'-')+'</div><div class="itemActions"><button class="soft" data-action="edit" data-id="'+esc(i.id)+'">Düzenle</button><button class="danger" data-action="delete" data-id="'+esc(i.id)+'">Sil</button></div></div>').join(''):'<div class="empty">Bu filtrelerde kayıt yok.</div>';renderBalance()}
function renderBalance(){let exp=[],ins=[],label='';if(balanceMode==='month'){const p=$('balanceMonth').value||mon();exp=x.filter(i=>String(i.date).slice(0,7)===p);ins=inc.filter(i=>String(i.date).slice(0,7)===p);const [y,m]=p.split('-').map(Number);label=new Intl.DateTimeFormat('tr-TR',{month:'long',year:'numeric'}).format(new Date(y,m-1,1));$('yearTableWrap').style.display='none'}else{const y=$('balanceYear').value||year();exp=x.filter(i=>String(i.date).slice(0,4)===y);ins=inc.filter(i=>String(i.date).slice(0,4)===y);label=y+' yılı';$('yearTableWrap').style.display='block';const mn=['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'];$('yearRows').innerHTML=mn.map((n,idx)=>{const mm=String(idx+1).padStart(2,'0'),p=y+'-'+mm,iv=sum(inc.filter(i=>String(i.date).slice(0,7)===p)),ev=sum(x.filter(i=>String(i.date).slice(0,7)===p)),nv=iv-ev;return'<tr><td>'+n+'</td><td>'+fmt(iv)+'</td><td>'+fmt(ev)+'</td><td class="'+(nv>0?'netPos':nv<0?'netNeg':'')+'">'+fmt(nv)+'</td></tr>'}).join('')}
const iv=sum(ins),ev=sum(exp),nv=iv-ev;$('balIncome').textContent=fmt(iv);$('balExpense').textContent=fmt(ev);$('balNet').textContent=fmt(nv);$('balNet').className='val '+(nv>0?'good':nv<0?'bad':'');const margin=iv>0?nv/iv*100:0;$('monthlySummary').innerHTML='<div class="summaryLine"><span>Dönem</span><strong>'+esc(label)+'</strong></div><div class="summaryLine"><span>Gelir</span><strong class="good">'+fmt(iv)+'</strong></div><div class="summaryLine"><span>Gider</span><strong class="bad">'+fmt(ev)+'</strong></div><div class="summaryLine total"><span>Net '+(nv>=0?'kâr':'zarar')+'</span><strong class="'+(nv>0?'good':nv<0?'bad':'')+'">'+fmt(nv)+'</strong></div><div class="summaryLine"><span>Kâr / gelir oranı</span><strong>'+Math.round(margin)+'%</strong></div>';const p=balanceMode==='month'?($('balanceMonth').value||mon()):($('balanceYear').value||year());let li=inc.filter(i=>balanceMode==='month'?String(i.date).slice(0,7)===p:String(i.date).slice(0,4)===p).sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('incomeListInfo').textContent=li.length+' kayıt • '+fmt(sum(li));$('incomeItems').innerHTML=li.length?li.map(i=>'<div class="item"><div class="itemTop"><div><div class="itemCat">'+esc(i.cat)+'</div><div class="itemDesc">'+esc(i.desc||'-')+'</div></div><div class="itemAmt good">+'+fmt(i.amount)+'</div></div><div class="meta">'+esc(i.date)+'</div><div class="itemActions"><button class="danger" data-income-delete="'+esc(i.id)+'">Sil</button></div></div>').join(''):'<div class="empty">Bu dönem için gelir kaydı yok.</div>'}
render();updateLockUI();if(localStorage.getItem(L))$('lock').classList.add('on');if('serviceWorker'in navigator){try{const reg=await navigator.serviceWorker.register('sw.js?v=4');reg.update()}catch{}}})();