import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
const {PGlite}=createRequire(import.meta.url)('@electric-sql/pglite');
const db=new PGlite();
const owner='11111111-1111-4111-8111-111111111111', other='22222222-2222-4222-8222-222222222222', id='33333333-3333-4333-8333-333333333333';
await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security;
create function storage.foldername(text) returns text[] language sql immutable as $$select string_to_array($1,'/')$$;
grant usage on schema auth,public,storage to anon,authenticated;
grant select,insert,update,delete on storage.objects to authenticated;
insert into auth.users values('${owner}'),('${other}');`);
const migration=await readFile(new URL('../supabase/migrations/202610070001_receipts.sql',import.meta.url),'utf8');
await db.exec(migration);
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${owner}',false);`);
await db.query(`insert into public.receipts(id,owner_id,image_path,image_hash,image_mime) values($1,$2,$3,$4,'image/png')`,[id,owner,owner+'/'+id+'.png','a'.repeat(64)]);
await assert.rejects(()=>db.query(`insert into public.receipts(owner_id,image_path,image_hash,image_mime) values($1,$2,$3,'image/png')`,[other,other+'/foreign.png','b'.repeat(64)]),/row-level security/);
await assert.rejects(()=>db.query(`insert into public.receipts(owner_id,image_path,image_hash,image_mime) values($1,$2,$3,'image/png')`,[owner,owner+'/duplicate.png','a'.repeat(64)]),/unique constraint/);
await assert.rejects(()=>db.query(`insert into storage.objects(bucket_id,name) values('receipts',$1)`,[other+'/not-mine.png']),/row-level security/);
await db.query(`insert into storage.objects(bucket_id,name) values('receipts',$1)`,[owner+'/'+id+'.png']);
const confirm=()=>db.query(`select (public.confirm_receipt($1,'Migros','2026-10-07',1284.50,'Market','Kredi Kartı','Alışveriş',$2::jsonb)).*`,[id,JSON.stringify([{name:'Süt',quantity:2,total:85.50}])]);
await assert.rejects(confirm,/Yükleme/);
await db.query(`update public.receipts set status='uploaded' where id=$1`,[id]);
const claim=await db.query(`select public.begin_receipt_analysis($1) as token`,[id]);assert.ok(claim.rows[0].token);
await assert.rejects(()=>db.query(`select public.begin_receipt_analysis($1)`,[id]),/zaten okunuyor/);
await assert.rejects(confirm,/Yükleme/);
await db.query(`update public.receipts set status='analyzed',analysis_token=null where id=$1`,[id]);
const confirmed=await confirm();assert.equal(confirmed.rows[0].status,'confirmed');assert.equal(Number(confirmed.rows[0].amount),1284.50);
await confirm();assert.equal(Number((await db.query('select count(*) n from public.receipts')).rows[0].n),1);
await assert.rejects(()=>db.query(`select public.begin_receipt_analysis($1)`,[id]),/durumda okunamaz/);
await db.exec(`select set_config('request.jwt.claim.sub','${other}',false);`);
assert.equal((await db.query('select * from public.receipts')).rows.length,0);
assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await assert.rejects(confirm,/bulunamadı/);
assert.equal((await db.query(`delete from public.receipts where id=$1 returning id`,[id])).rows.length,0);
await db.exec(`set role anon;`);
await assert.rejects(()=>db.query('select * from public.receipts'),/permission denied/);
await assert.rejects(()=>db.query(`select public.begin_receipt_analysis($1)`,[id]),/permission denied/);
await db.exec('reset role;');
await db.exec(migration); // Reapplying setup must preserve the receipt and its private bucket.
assert.equal(Number((await db.query('select count(*) n from public.receipts')).rows[0].n),1);
assert.equal((await db.query(`select public from storage.buckets where id='receipts'`)).rows[0].public,false);
await db.exec(`update public.receipt_analysis_usage set calls=50;update public.receipts set status='uploaded';set role authenticated;select set_config('request.jwt.claim.sub','${owner}',false);`);
await assert.rejects(()=>db.query(`select public.begin_receipt_analysis($1)`,[id]),/50 okuma/);
assert.equal((await db.query(`select status from public.receipts where id=$1`,[id])).rows[0].status,'uploaded');
await db.close();console.log('PASS: PostgreSQL migration, RLS isolation, private storage policies, duplicate constraint, confirmation validation, analysis lease, daily quota, anonymous denial, idempotent setup.');
